config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get 'home/new'
  #get 'home/new' => 'home#new'

  post 'home/create'
  
  get 'home/destroy/:post_id' ,to: 'home#destroy' ,as: 'post_destroy'

  get 'home/edit/:post_id' => 'home#edit'
  
  post 'home/update/:post_id' => 'home#update'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
  end

  def create
    @post = Post.new
    @post.title = params[:post_title]
    @post.content = params[:post_content]
    @post.save
    
    redirect_to '/'
  end
  
  def destroy
    post = Post.find(params[:post_id])
    post.destroy
    redirect_to '/'
  end
  
  def edit
    @post = Post.find(params[:post_id])
  end
  
  def update
    post = Post.find(params[:post_id])
    post.title = params[:post_title]
    post.content = params[:post_content]
    post.save
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/create.html.erb
<h1>Home#create</h1>
<p>Find me in app/views/home/create.html.erb</p>

<%=params%>

app/views/home/edit.html.erb
<form action='/home/update/<%=@post.id%>' method='post'>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    Name <input type='text' name='post_title' value=<%=@post.title%>> <br>
    Content <textarea name='post_content'><%=@post.content%></textarea>
    <input type='submit' value='submit'>
</form>

app/views/home/index.html.erb
<h1>List</h1>
<a href='home/new'>new</a>

<br><br>

<%@posts.each do |p|%>
    title: <%=p.title%>
    content: <%=p.content%>
    <a href="/home/destroy/<%=p.id%>">Delete1</a>
    <%=link_to post_destroy_path(post_id: p.id) do%>
        <button>Delete2</button>
    <%end%>
    <a href='/home/edit/<%=p.id%>'>Update</a>
    <br><br>
<%end%>

app/views/home/new.html.erb
<h1>Home#new</h1>
<form action='/home/create' method='post'>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    Name <input type='text' name='post_title'><br>
    Content <textarea name='post_content'></textarea>
    <input type='submit' value='submit'>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Note</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>